name = "composer-oss-worker"
main = "worker/src/index.ts"
compatibility_date = "2023-12-06"

[vars]
PUBLIC_ACCESS_TO_INDEX = true
PUBLIC_ACCESS_TO_JSON = false
CHECK_FILE_RESTRICTIONS = true
CHECK_EXTRA_JSON_RESTRICTIONS = true
STORE_PASSWORDS_HASHED = true
ENABLE_USER_ENDPOINT = true

[[routes]]
pattern = "composer.pdfsystems.dev"
custom_domain = true

[[kv_namespaces]]
binding = "AUTH"
id = "58c7fcd966b246c5bac72fca8888e044"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "pdf-composer"
